#!/bin/bash

# config task for zookeeper 

hosts=('10.10.1.1' '10.10.1.2' '10.10.1.3')
pssh -h cloud -P -t 10000 rm -f /users/dporte7/lucene-solr/zookeeper-3.4.13/conf/zoo.cfg
pscp -h cloud ./templates/zoo.cfg /users/dporte7/lucene-solr/zookeeper-3.4.13/conf

for i in 0 1 2
do
	pssh -P -h node$i "touch /var/lib/zookeeper/myid;echo '$i'>/var/lib/zookeeper/myid;cat /var/lib/zookeeper/myid"
done
echo "done"
